// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/api/[tokType]-[token]/[outputFmt]/[composition]/[url].tsx";
import * as $6 from "./routes/api/[tokType]-[token]/[outputFmt]/[composition]/index.tsx";
import * as $7 from "./routes/api/[tokType]-[token]/[outputFmt]/[composition]/preview/[url].tsx";
import * as $8 from "./routes/api/[tokType]-[token]/[outputFmt]/[composition]/preview/index.tsx";
import * as $9 from "./routes/api/[tokType]-[token]/[outputFmt]/index.tsx";
import * as $10 from "./routes/api/[tokType]-[token]/index.tsx";
import * as $11 from "./routes/api/index.tsx";
import * as $12 from "./routes/app/actions/index.tsx";
import * as $13 from "./routes/app/data/index.tsx";
import * as $14 from "./routes/app/feeds/add.tsx";
import * as $15 from "./routes/app/feeds/index.tsx";
import * as $16 from "./routes/app/following.ts";
import * as $17 from "./routes/app/functions/index.tsx";
import * as $18 from "./routes/app/index.tsx";
import * as $19 from "./routes/app/organizations/index.tsx";
import * as $20 from "./routes/app/reader/index.tsx";
import * as $21 from "./routes/app/team/index.tsx";
import * as $22 from "./routes/ast/[composition]/[...url].tsx";
import * as $23 from "./routes/ast/[composition]/index.tsx";
import * as $24 from "./routes/ast/[url].tsx";
import * as $25 from "./routes/ast/index.tsx";
import * as $26 from "./routes/earlybird.tsx";
import * as $27 from "./routes/following.tsx";
import * as $28 from "./routes/hero.tsx";
import * as $29 from "./routes/home.tsx";
import * as $30 from "./routes/homey.tsx";
import * as $31 from "./routes/index.tsx";
import * as $32 from "./routes/login.tsx";
import * as $33 from "./routes/logout.tsx";
import * as $34 from "./routes/posts/[year]/[slug].tsx";
import * as $35 from "./routes/posts/[year]/index.tsx";
import * as $36 from "./routes/posts/components.tsx";
import * as $37 from "./routes/posts/index.tsx";
import * as $38 from "./routes/posts/tags/[tag].tsx";
import * as $39 from "./routes/profile.tsx";
import * as $40 from "./routes/read.tsx";
import * as $41 from "./routes/settings.tsx";
import * as $42 from "./routes/team.tsx";
import * as $43 from "./routes/testing.tsx";
import * as $44 from "./routes/user/index.ts";
import * as $45 from "./routes/user/register.tsx";
import * as $$0 from "./islands/AppShellMenuBar.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/compositionForm.tsx";
import * as $$3 from "./islands/heroicon-menu.tsx";
import * as $$4 from "./islands/hooks/useFocusedButtons.tsx";
import * as $$5 from "./islands/navbar.tsx";
import * as $$6 from "./islands/preview.tsx";
import * as $$7 from "./islands/public-about-hero.tsx";
import * as $$8 from "./islands/public-navbar.tsx";
import * as $$9 from "./islands/public-signup.tsx";
import * as $$10 from "./islands/textArea-previewable.tsx";

const manifest = {
	routes: {
		"./routes/_404.tsx": $0,
		"./routes/_500.tsx": $1,
		"./routes/_app.tsx": $2,
		"./routes/_middleware.ts": $3,
		"./routes/about.tsx": $4,
		"./routes/api/[tokType]-[token]/[outputFmt]/[composition]/[url].tsx": $5,
		"./routes/api/[tokType]-[token]/[outputFmt]/[composition]/index.tsx": $6,
		"./routes/api/[tokType]-[token]/[outputFmt]/[composition]/preview/[url].tsx": $7,
		"./routes/api/[tokType]-[token]/[outputFmt]/[composition]/preview/index.tsx": $8,
		"./routes/api/[tokType]-[token]/[outputFmt]/index.tsx": $9,
		"./routes/api/[tokType]-[token]/index.tsx": $10,
		"./routes/api/index.tsx": $11,
		"./routes/app/actions/index.tsx": $12,
		"./routes/app/data/index.tsx": $13,
		"./routes/app/feeds/add.tsx": $14,
		"./routes/app/feeds/index.tsx": $15,
		"./routes/app/following.ts": $16,
		"./routes/app/functions/index.tsx": $17,
		"./routes/app/index.tsx": $18,
		"./routes/app/organizations/index.tsx": $19,
		"./routes/app/reader/index.tsx": $20,
		"./routes/app/team/index.tsx": $21,
		"./routes/ast/[composition]/[...url].tsx": $22,
		"./routes/ast/[composition]/index.tsx": $23,
		"./routes/ast/[url].tsx": $24,
		"./routes/ast/index.tsx": $25,
		"./routes/earlybird.tsx": $26,
		"./routes/following.tsx": $27,
		"./routes/hero.tsx": $28,
		"./routes/home.tsx": $29,
		"./routes/homey.tsx": $30,
		"./routes/index.tsx": $31,
		"./routes/login.tsx": $32,
		"./routes/logout.tsx": $33,
		"./routes/posts/[year]/[slug].tsx": $34,
		"./routes/posts/[year]/index.tsx": $35,
		"./routes/posts/components.tsx": $36,
		"./routes/posts/index.tsx": $37,
		"./routes/posts/tags/[tag].tsx": $38,
		"./routes/profile.tsx": $39,
		"./routes/read.tsx": $40,
		"./routes/settings.tsx": $41,
		"./routes/team.tsx": $42,
		"./routes/testing.tsx": $43,
		"./routes/user/index.ts": $44,
		"./routes/user/register.tsx": $45,
	},
	islands: {
		"./islands/AppShellMenuBar.tsx": $$0,
		"./islands/Counter.tsx": $$1,
		"./islands/compositionForm.tsx": $$2,
		"./islands/heroicon-menu.tsx": $$3,
		"./islands/hooks/useFocusedButtons.tsx": $$4,
		"./islands/navbar.tsx": $$5,
		"./islands/preview.tsx": $$6,
		"./islands/public-about-hero.tsx": $$7,
		"./islands/public-navbar.tsx": $$8,
		"./islands/public-signup.tsx": $$9,
		"./islands/textArea-previewable.tsx": $$10,
	},
	baseUrl: import.meta.url,
};

export default manifest;
