export const mockJSON = `
{
    "status": "OK",
    "code": 200,
    "total": 10,
    "data": [
      {
        "id": 1,
        "firstname": "Dale",
        "lastname": "Schneider",
        "email": "emilia23@labadie.biz",
        "phone": "+7822685333403",
        "birthday": "2005-11-24",
        "gender": "male",
        "address": {
          "id": 0,
          "street": "53138 Beatty Falls",
          "streetName": "Bergnaum Ways",
          "buildingNumber": "93754",
          "city": "Port Hopeside",
          "zipcode": "92591",
          "country": "Djibouti",
          "county_code": "PF",
          "latitude": -65.349662,
          "longitude": -42.131754
        },
        "website": "http://langosh.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 2,
        "firstname": "Liana",
        "lastname": "Champlin",
        "email": "parisian.lindsay@krajcik.net",
        "phone": "+5970513792582",
        "birthday": "1998-12-12",
        "gender": "female",
        "address": {
          "id": 0,
          "street": "10329 Cary River",
          "streetName": "Reinger Ways",
          "buildingNumber": "5798",
          "city": "Kristinland",
          "zipcode": "50772",
          "country": "Saint Vincent and the Grenadines",
          "county_code": "TZ",
          "latitude": -54.669444,
          "longitude": 19.438566
        },
        "website": "http://tremblay.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 3,
        "firstname": "Jorge",
        "lastname": "Kub",
        "email": "willms.destin@flatley.com",
        "phone": "+9827681492063",
        "birthday": "1938-06-27",
        "gender": "male",
        "address": {
          "id": 0,
          "street": "9999 Hartmann Falls Suite 256",
          "streetName": "Delbert Island",
          "buildingNumber": "4751",
          "city": "South Giuseppefort",
          "zipcode": "69670-5136",
          "country": "Nigeria",
          "county_code": "BY",
          "latitude": 31.009958,
          "longitude": 123.791489
        },
        "website": "http://bradtke.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 4,
        "firstname": "Jacky",
        "lastname": "Schuster",
        "email": "elyse.gerlach@marks.com",
        "phone": "+2604358560787",
        "birthday": "1987-04-30",
        "gender": "female",
        "address": {
          "id": 0,
          "street": "502 Anthony Vista Suite 806",
          "streetName": "Kuhn Run",
          "buildingNumber": "539",
          "city": "Omerbury",
          "zipcode": "37174",
          "country": "Benin",
          "county_code": "MQ",
          "latitude": -2.139341,
          "longitude": -140.634419
        },
        "website": "http://lind.biz",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 5,
        "firstname": "Zachary",
        "lastname": "Schinner",
        "email": "taya.bauch@yahoo.com",
        "phone": "+3820987013080",
        "birthday": "1996-08-10",
        "gender": "male",
        "address": {
          "id": 0,
          "street": "9366 Homenick Knolls",
          "streetName": "Leuschke Falls",
          "buildingNumber": "2957",
          "city": "Luettgenchester",
          "zipcode": "59242",
          "country": "Angola",
          "county_code": "AZ",
          "latitude": 30.037155,
          "longitude": -46.003147
        },
        "website": "http://runolfsson.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 6,
        "firstname": "Emory",
        "lastname": "Hauck",
        "email": "gisselle29@yahoo.com",
        "phone": "+7101228853864",
        "birthday": "1999-01-27",
        "gender": "male",
        "address": {
          "id": 0,
          "street": "42066 Vallie Rest",
          "streetName": "Schinner Expressway",
          "buildingNumber": "485",
          "city": "Gretastad",
          "zipcode": "65616-9590",
          "country": "Canada",
          "county_code": "UM",
          "latitude": 74.531066,
          "longitude": 115.913619
        },
        "website": "http://brakus.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 7,
        "firstname": "Pearl",
        "lastname": "Beahan",
        "email": "jerrold78@rippin.info",
        "phone": "+4651590705131",
        "birthday": "1952-08-17",
        "gender": "female",
        "address": {
          "id": 0,
          "street": "710 Orn Heights Suite 481",
          "streetName": "McLaughlin Plains",
          "buildingNumber": "27245",
          "city": "Connside",
          "zipcode": "06628",
          "country": "Mayotte",
          "county_code": "JP",
          "latitude": -75.807194,
          "longitude": -117.204679
        },
        "website": "http://gusikowski.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 8,
        "firstname": "Rosa",
        "lastname": "Willms",
        "email": "sam51@larkin.org",
        "phone": "+7525113579000",
        "birthday": "1969-03-19",
        "gender": "female",
        "address": {
          "id": 0,
          "street": "15175 Lelah Ridges",
          "streetName": "Brandy Haven",
          "buildingNumber": "2612",
          "city": "Watsicahaven",
          "zipcode": "85242",
          "country": "Korea",
          "county_code": "LT",
          "latitude": -21.646648,
          "longitude": 155.020055
        },
        "website": "http://huels.com",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 9,
        "firstname": "Matilda",
        "lastname": "Brekke",
        "email": "haley.daugherty@hotmail.com",
        "phone": "+1094467531874",
        "birthday": "1966-03-09",
        "gender": "female",
        "address": {
          "id": 0,
          "street": "30589 Eulah Lights",
          "streetName": "Jaylin Alley",
          "buildingNumber": "918",
          "city": "East Ellie",
          "zipcode": "43340-6052",
          "country": "Falkland Islands (Malvinas)",
          "county_code": "HT",
          "latitude": -80.888323,
          "longitude": 172.871614
        },
        "website": "http://grady.org",
        "image": "http://placeimg.com/640/480/people"
      },
      {
        "id": 10,
        "firstname": "Danial",
        "lastname": "Murazik",
        "email": "lane86@hirthe.info",
        "phone": "+9808392453342",
        "birthday": "2019-02-05",
        "gender": "male",
        "address": {
          "id": 0,
          "street": "638 Quitzon Loop",
          "streetName": "Fay Manor",
          "buildingNumber": "6622",
          "city": "Ressieland",
          "zipcode": "12935-5464",
          "country": "Dominica",
          "county_code": "NP",
          "latitude": -64.174788,
          "longitude": 176.804198
        },
        "website": "http://mueller.biz",
        "image": "http://placeimg.com/640/480/people"
      }
    ]
  }`;
