# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production # Dev | Red | Orange | Yellow | Green | Blue | Violet 

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        # uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.37.0"

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test
        env:          
          AES_GCM_K: ${{ secrets.AES_GCM_K }}
          AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AWS_DYN_TABLE_MEGA: ${{ vars.AWS_DYN_TABLE_MEGA }}
          AWS_DYN_TABLE_SESSION: ${{ secrets.AWS_DYN_TABLE_SESSION }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_POLLY_BUCKET: ${{ vars.AWS_POLLY_BUCKET }}
          AWS_POLLY_PREFIX: ${{ vars.AWS_POLLY_PREFIX }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          CLOUDFLARE_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          CLOUDFLARE_FEEDCITY_ACCESS_KEY: ${{ secrets.CLOUDFLARE_FEEDCITY_ACCESS_KEY }}
          CLOUDFLARE_FEEDCITY_ACCESS_SECRET: ${{ secrets.CLOUDFLARE_FEEDCITY_ACCESS_SECRET }}
          CLOUDFLARE_FEEDCITY_TOKEN: ${{ secrets.CLOUDFLARE_FEEDCITY_TOKEN }}
          CLOUDFLARE_ZONEID: ${{ secrets.CLOUDFLARE_ZONEID }}
          JWT_KEY_ALG: ${{ secrets.JWT_KEY_ALG }}
          JWT_KEY_CRV: ${{ secrets.JWT_KEY_CRV }}
          JWT_KEY_D_PRIVATE: ${{ secrets.JWT_KEY_D_PRIVATE }}
          JWT_KEY_EXT: ${{ vars.JWT_KEY_EXT }}
          JWT_KEY_ID: ${{ secrets.JWT_KEY_ID }}
          JWT_KEY_KTY: ${{ secrets.JWT_KEY_KTY }}
          JWT_KEY_OPS_PRIVATE: ${{ vars.JWT_KEY_OPS_PRIVATE }}
          JWT_KEY_OPS_PUBLIC: ${{ vars.JWT_KEY_OPS_PUBLIC }}
          JWT_KEY_X: ${{ secrets.JWT_KEY_X }}
          JWT_KEY_Y: ${{ secrets.JWT_KEY_Y }}
          OPENAI_ORGID: ${{ secrets.OPENAI_ORGID }}
          OPENAI_PROD_KEY: ${{ secrets.OPENAI_PROD_KEY }}
          OPENAI_TEST_KEY: ${{ secrets.OPENAI_TEST_KEY }}
          RSA_KEY_E: ${{ secrets.RSA_KEY_E }}
          RSA_KEY_N: ${{ secrets.RSA_KEY_N }}
          RSA_KEY_PRIVATE_D: ${{ secrets.RSA_KEY_PRIVATE_D }}
          RSA_KEY_PRIVATE_DP: ${{ secrets.RSA_KEY_PRIVATE_DP }}
          RSA_KEY_PRIVATE_DQ: ${{ secrets.RSA_KEY_PRIVATE_DQ }}
          RSA_KEY_PRIVATE_P: ${{ secrets.RSA_KEY_PRIVATE_P }}
          RSA_KEY_PRIVATE_Q: ${{ secrets.RSA_KEY_PRIVATE_Q }}
          RSA_KEY_PRIVATE_QI: ${{ secrets.RSA_KEY_PRIVATE_QI }}
          STRIPE_ACCT_ID: ${{ secrets.STRIPE_ACCT_ID }}
          STRIPE_PUBLISHED_TOKEN: ${{ secrets.STRIPE_PUBLISHED_TOKEN }}
          STRIPE_SECRET_TOKEN: ${{ secrets.STRIPE_SECRET_TOKEN }}
          STRIPE_TEST_PUBLISHED_TOKEN: ${{ secrets.STRIPE_TEST_PUBLISHED_TOKEN }}
          STRIPE_TEST_SECRET_TOKEN: ${{ secrets.STRIPE_TEST_SECRET_TOKEN }}